// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9TH61zjuBMq6qiNT59wbEBbLRjoCjwb8',
    appId: '1:608175951008:web:40f1239ec04a453fe28dc5',
    messagingSenderId: '608175951008',
    projectId: 'chat-app-with-websocket',
    authDomain: 'chat-app-with-websocket.firebaseapp.com',
    storageBucket: 'chat-app-with-websocket.appspot.com',
    measurementId: 'G-V1EWZVFR1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDlBRxgwSAu06Vnq0JaQ4Nf01cgVVHsL0',
    appId: '1:608175951008:android:df88e5210b59dd1ae28dc5',
    messagingSenderId: '608175951008',
    projectId: 'chat-app-with-websocket',
    storageBucket: 'chat-app-with-websocket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD76syFbqdoyPg0LkwiLs93v3YQjSju92Q',
    appId: '1:608175951008:ios:51eeecc160b5c8c3e28dc5',
    messagingSenderId: '608175951008',
    projectId: 'chat-app-with-websocket',
    storageBucket: 'chat-app-with-websocket.appspot.com',
    iosBundleId: 'com.example.chatUsingWebsocket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD76syFbqdoyPg0LkwiLs93v3YQjSju92Q',
    appId: '1:608175951008:ios:3bd961ca6cf50e4be28dc5',
    messagingSenderId: '608175951008',
    projectId: 'chat-app-with-websocket',
    storageBucket: 'chat-app-with-websocket.appspot.com',
    iosBundleId: 'com.example.chatUsingWebsocket.RunnerTests',
  );
}
